dataset:
  train_path: pdb_bind_data.csv
  test_path: pdb_bind_data.csv
  data_dir: ["/gs/hs0/tga-science/murata", "v2019-other-PL"]
preprocess:
  grid_size: 20
  cell_size: 1
model:
  name: vae
  experiment_id: 0
optimizer:
  algorithm: Adam
  learning_rate: 0.01
training:
  name: Default
  gpu_num: 1
  batch_size: 30
  epoch: 20
hydra:
  run:
    dir: output/
