dataset:
  train:
    index_file: v2020_index.csv
    data_dir: ["/mnt/d/", "v2020_PL_all"]
    numpy_data_dir: ["/mnt/d/", "v2020-points"]
  test:
    index_file: v2020_test_index.csv
    data_dir: ["test_data"]
    ligand_file: crystal_ligand.mol2
    receptor_file: receptor.pdb

preprocess:
  grid_size: 32
  cell_size: 0.5
model:
  type: "multi"
  model_dir: "models"
  output_channel: 3 # if model.type=="normal" then 1 else if model.type=="multi" then 3 (C, O, N)
optimizer:
  algorithm: Adam
  learning_rate: 0.01
optuna:
  n_trials: 100
training:
  name: Default
  gpu_num: 1
  batch_size: 20
  epoch: 20
  timeout: 8 #hours
job_id: 0
cross_validation:
  ith: -1
hydra:
  run:
    dir: output/
